FROM golang:1.18.2-alpine
RUN     mkdir -p /app
WORKDIR /app
# COPY ./pkg ./proto ./go.mod ./go.sum ./main.go .
COPY . .
RUN    go mod download
RUN    go build -o app
RUN    go run ./pkg/migrate/migrate.go
EXPOSE 8081
ENTRYPOINT  ["./app"]

# > docker build -t member_service .
# > docker run -d --name member_service -p 8081:8081 member_service