FROM golang:1.18.2-alpine
RUN     mkdir -p /app
WORKDIR /app
COPY . .
RUN    go mod download
RUN    go build -o app
EXPOSE 9000
ENTRYPOINT  ["./app"]

# > docker build -t main_service .
# > docker run -d --name main_service -p 8081:8081 main_service