// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tokenModule

// Injectors from wire.go:

func InitTokenController() *TokenController {
	tokenService := NewTokenService()
	tokenController := NewTokenController(tokenService)
	return tokenController
}
